// Mocks generated by Mockito 5.4.5 from annotations
// in paperclip2/test/cloud_save_auth_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:convert' as _i13;
import 'dart:typed_data' as _i14;
import 'dart:ui' as _i18;

import 'package:flutter/material.dart' as _i17;
import 'package:google_sign_in/google_sign_in.dart' as _i2;
import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart'
    as _i10;
import 'package:http/http.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:paperclip2/managers/metal_manager.dart' as _i5;
import 'package:paperclip2/managers/production_manager.dart' as _i6;
import 'package:paperclip2/managers/statistics_manager.dart' as _i4;
import 'package:paperclip2/models/game_config.dart' as _i16;
import 'package:paperclip2/models/game_state.dart' as _i15;
import 'package:paperclip2/models/market.dart' as _i8;
import 'package:paperclip2/models/player_manager.dart' as _i7;
import 'package:paperclip2/models/progression_system.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGoogleSignInAuthentication_0 extends _i1.SmartFake
    implements _i2.GoogleSignInAuthentication {
  _FakeGoogleSignInAuthentication_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_1 extends _i1.SmartFake implements _i3.Response {
  _FakeResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_2 extends _i1.SmartFake
    implements _i3.StreamedResponse {
  _FakeStreamedResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStatisticsManager_3 extends _i1.SmartFake
    implements _i4.StatisticsManager {
  _FakeStatisticsManager_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMetalManager_4 extends _i1.SmartFake implements _i5.MetalManager {
  _FakeMetalManager_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductionManager_5 extends _i1.SmartFake
    implements _i6.ProductionManager {
  _FakeProductionManager_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePlayerManager_6 extends _i1.SmartFake implements _i7.PlayerManager {
  _FakePlayerManager_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMarketManager_7 extends _i1.SmartFake implements _i8.MarketManager {
  _FakeMarketManager_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLevelSystem_8 extends _i1.SmartFake implements _i9.LevelSystem {
  _FakeLevelSystem_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMissionSystem_9 extends _i1.SmartFake implements _i9.MissionSystem {
  _FakeMissionSystem_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_10 extends _i1.SmartFake implements Duration {
  _FakeDuration_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GoogleSignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignIn extends _i1.Mock implements _i2.GoogleSignIn {
  MockGoogleSignIn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.SignInOption get signInOption =>
      (super.noSuchMethod(
            Invocation.getter(#signInOption),
            returnValue: _i10.SignInOption.standard,
          )
          as _i10.SignInOption);

  @override
  List<String> get scopes =>
      (super.noSuchMethod(Invocation.getter(#scopes), returnValue: <String>[])
          as List<String>);

  @override
  bool get forceCodeForRefreshToken =>
      (super.noSuchMethod(
            Invocation.getter(#forceCodeForRefreshToken),
            returnValue: false,
          )
          as bool);

  @override
  _i11.Stream<_i2.GoogleSignInAccount?> get onCurrentUserChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onCurrentUserChanged),
            returnValue: _i11.Stream<_i2.GoogleSignInAccount?>.empty(),
          )
          as _i11.Stream<_i2.GoogleSignInAccount?>);

  @override
  _i11.Future<_i2.GoogleSignInAccount?> signInSilently({
    bool? suppressErrors = true,
    bool? reAuthenticate = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInSilently, [], {
              #suppressErrors: suppressErrors,
              #reAuthenticate: reAuthenticate,
            }),
            returnValue: _i11.Future<_i2.GoogleSignInAccount?>.value(),
          )
          as _i11.Future<_i2.GoogleSignInAccount?>);

  @override
  _i11.Future<bool> isSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isSignedIn, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<_i2.GoogleSignInAccount?> signIn() =>
      (super.noSuchMethod(
            Invocation.method(#signIn, []),
            returnValue: _i11.Future<_i2.GoogleSignInAccount?>.value(),
          )
          as _i11.Future<_i2.GoogleSignInAccount?>);

  @override
  _i11.Future<_i2.GoogleSignInAccount?> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i11.Future<_i2.GoogleSignInAccount?>.value(),
          )
          as _i11.Future<_i2.GoogleSignInAccount?>);

  @override
  _i11.Future<_i2.GoogleSignInAccount?> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i11.Future<_i2.GoogleSignInAccount?>.value(),
          )
          as _i11.Future<_i2.GoogleSignInAccount?>);

  @override
  _i11.Future<bool> requestScopes(List<String>? scopes) =>
      (super.noSuchMethod(
            Invocation.method(#requestScopes, [scopes]),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  _i11.Future<bool> canAccessScopes(
    List<String>? scopes, {
    String? accessToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #canAccessScopes,
              [scopes],
              {#accessToken: accessToken},
            ),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);
}

/// A class which mocks [GoogleSignInAccount].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockGoogleSignInAccount extends _i1.Mock
    implements _i2.GoogleSignInAccount {
  MockGoogleSignInAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i12.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  _i11.Future<_i2.GoogleSignInAuthentication> get authentication =>
      (super.noSuchMethod(
            Invocation.getter(#authentication),
            returnValue: _i11.Future<_i2.GoogleSignInAuthentication>.value(
              _FakeGoogleSignInAuthentication_0(
                this,
                Invocation.getter(#authentication),
              ),
            ),
          )
          as _i11.Future<_i2.GoogleSignInAuthentication>);

  @override
  _i11.Future<Map<String, String>> get authHeaders =>
      (super.noSuchMethod(
            Invocation.getter(#authHeaders),
            returnValue: _i11.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i11.Future<Map<String, String>>);

  @override
  _i11.Future<void> clearAuthCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAuthCache, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [GoogleSignInAuthentication].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInAuthentication extends _i1.Mock
    implements _i2.GoogleSignInAuthentication {
  MockGoogleSignInAuthentication() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i3.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i3.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i11.Future<_i3.Response>.value(
              _FakeResponse_1(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i11.Future<_i3.Response>);

  @override
  _i11.Future<_i3.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i11.Future<_i3.Response>.value(
              _FakeResponse_1(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i11.Future<_i3.Response>);

  @override
  _i11.Future<_i3.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i11.Future<_i3.Response>.value(
              _FakeResponse_1(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i11.Future<_i3.Response>);

  @override
  _i11.Future<_i3.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i11.Future<_i3.Response>.value(
              _FakeResponse_1(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i11.Future<_i3.Response>);

  @override
  _i11.Future<_i3.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i11.Future<_i3.Response>.value(
              _FakeResponse_1(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i11.Future<_i3.Response>);

  @override
  _i11.Future<_i3.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i13.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i11.Future<_i3.Response>.value(
              _FakeResponse_1(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i11.Future<_i3.Response>);

  @override
  _i11.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i11.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i11.Future<String>);

  @override
  _i11.Future<_i14.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i11.Future<_i14.Uint8List>.value(_i14.Uint8List(0)),
          )
          as _i11.Future<_i14.Uint8List>);

  @override
  _i11.Future<_i3.StreamedResponse> send(_i3.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i11.Future<_i3.StreamedResponse>.value(
              _FakeStreamedResponse_2(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i11.Future<_i3.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GameState].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameState extends _i1.Mock implements _i15.GameState {
  MockGameState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set marketTimer(_i11.Timer? _marketTimer) => super.noSuchMethod(
    Invocation.setter(#marketTimer, _marketTimer),
    returnValueForMissingStub: null,
  );

  @override
  _i4.StatisticsManager get statistics =>
      (super.noSuchMethod(
            Invocation.getter(#statistics),
            returnValue: _FakeStatisticsManager_3(
              this,
              Invocation.getter(#statistics),
            ),
          )
          as _i4.StatisticsManager);

  @override
  bool get isInCrisisMode =>
      (super.noSuchMethod(
            Invocation.getter(#isInCrisisMode),
            returnValue: false,
          )
          as bool);

  @override
  bool get crisisTransitionComplete =>
      (super.noSuchMethod(
            Invocation.getter(#crisisTransitionComplete),
            returnValue: false,
          )
          as bool);

  @override
  _i5.MetalManager get metalManager =>
      (super.noSuchMethod(
            Invocation.getter(#metalManager),
            returnValue: _FakeMetalManager_4(
              this,
              Invocation.getter(#metalManager),
            ),
          )
          as _i5.MetalManager);

  @override
  _i5.MetalManager get resources =>
      (super.noSuchMethod(
            Invocation.getter(#resources),
            returnValue: _FakeMetalManager_4(
              this,
              Invocation.getter(#resources),
            ),
          )
          as _i5.MetalManager);

  @override
  _i6.ProductionManager get productionManager =>
      (super.noSuchMethod(
            Invocation.getter(#productionManager),
            returnValue: _FakeProductionManager_5(
              this,
              Invocation.getter(#productionManager),
            ),
          )
          as _i6.ProductionManager);

  @override
  _i16.GameMode get gameMode =>
      (super.noSuchMethod(
            Invocation.getter(#gameMode),
            returnValue: _i16.GameMode.INFINITE,
          )
          as _i16.GameMode);

  @override
  bool get showingCrisisView =>
      (super.noSuchMethod(
            Invocation.getter(#showingCrisisView),
            returnValue: false,
          )
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i7.PlayerManager get playerManager =>
      (super.noSuchMethod(
            Invocation.getter(#playerManager),
            returnValue: _FakePlayerManager_6(
              this,
              Invocation.getter(#playerManager),
            ),
          )
          as _i7.PlayerManager);

  @override
  _i8.MarketManager get marketManager =>
      (super.noSuchMethod(
            Invocation.getter(#marketManager),
            returnValue: _FakeMarketManager_7(
              this,
              Invocation.getter(#marketManager),
            ),
          )
          as _i8.MarketManager);

  @override
  _i9.LevelSystem get levelSystem =>
      (super.noSuchMethod(
            Invocation.getter(#levelSystem),
            returnValue: _FakeLevelSystem_8(
              this,
              Invocation.getter(#levelSystem),
            ),
          )
          as _i9.LevelSystem);

  @override
  _i9.MissionSystem get missionSystem =>
      (super.noSuchMethod(
            Invocation.getter(#missionSystem),
            returnValue: _FakeMissionSystem_9(
              this,
              Invocation.getter(#missionSystem),
            ),
          )
          as _i9.MissionSystem);

  @override
  Duration get competitivePlayTime =>
      (super.noSuchMethod(
            Invocation.getter(#competitivePlayTime),
            returnValue: _FakeDuration_10(
              this,
              Invocation.getter(#competitivePlayTime),
            ),
          )
          as Duration);

  @override
  int get totalTimePlayed =>
      (super.noSuchMethod(Invocation.getter(#totalTimePlayed), returnValue: 0)
          as int);

  @override
  int get totalPaperclipsProduced =>
      (super.noSuchMethod(
            Invocation.getter(#totalPaperclipsProduced),
            returnValue: 0,
          )
          as int);

  @override
  double get maintenanceCosts =>
      (super.noSuchMethod(
            Invocation.getter(#maintenanceCosts),
            returnValue: 0.0,
          )
          as double);

  @override
  String get formattedPlayTime =>
      (super.noSuchMethod(
            Invocation.getter(#formattedPlayTime),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#formattedPlayTime),
            ),
          )
          as String);

  @override
  Map<String, _i7.Upgrade> get upgrades =>
      (super.noSuchMethod(
            Invocation.getter(#upgrades),
            returnValue: <String, _i7.Upgrade>{},
          )
          as Map<String, _i7.Upgrade>);

  @override
  double get maxMetalStorage =>
      (super.noSuchMethod(Invocation.getter(#maxMetalStorage), returnValue: 0.0)
          as double);

  @override
  _i7.PlayerManager get player =>
      (super.noSuchMethod(
            Invocation.getter(#player),
            returnValue: _FakePlayerManager_6(this, Invocation.getter(#player)),
          )
          as _i7.PlayerManager);

  @override
  _i8.MarketManager get market =>
      (super.noSuchMethod(
            Invocation.getter(#market),
            returnValue: _FakeMarketManager_7(this, Invocation.getter(#market)),
          )
          as _i8.MarketManager);

  @override
  _i9.LevelSystem get level =>
      (super.noSuchMethod(
            Invocation.getter(#level),
            returnValue: _FakeLevelSystem_8(this, Invocation.getter(#level)),
          )
          as _i9.LevelSystem);

  @override
  double get autocliperCost =>
      (super.noSuchMethod(Invocation.getter(#autocliperCost), returnValue: 0.0)
          as double);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void handleCompetitiveGameEnd() => super.noSuchMethod(
    Invocation.method(#handleCompetitiveGameEnd, []),
    returnValueForMissingStub: null,
  );

  @override
  int calculateCompetitiveScore() =>
      (super.noSuchMethod(
            Invocation.method(#calculateCompetitiveScore, []),
            returnValue: 0,
          )
          as int);

  @override
  double calculateEfficiencyRating() =>
      (super.noSuchMethod(
            Invocation.method(#calculateEfficiencyRating, []),
            returnValue: 0.0,
          )
          as double);

  @override
  _i11.Future<bool> syncSavesToCloud() =>
      (super.noSuchMethod(
            Invocation.method(#syncSavesToCloud, []),
            returnValue: _i11.Future<bool>.value(false),
          )
          as _i11.Future<bool>);

  @override
  void enterCrisisMode() => super.noSuchMethod(
    Invocation.method(#enterCrisisMode, []),
    returnValueForMissingStub: null,
  );

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetMarket() => super.noSuchMethod(
    Invocation.method(#resetMarket, []),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> prepareGameData() =>
      (super.noSuchMethod(
            Invocation.method(#prepareGameData, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void loadGameData(Map<String, dynamic>? gameData) => super.noSuchMethod(
    Invocation.method(#loadGameData, [gameData]),
    returnValueForMissingStub: null,
  );

  @override
  void processProduction() => super.noSuchMethod(
    Invocation.method(#processProduction, []),
    returnValueForMissingStub: null,
  );

  @override
  void checkResourceCrisis() => super.noSuchMethod(
    Invocation.method(#checkResourceCrisis, []),
    returnValueForMissingStub: null,
  );

  @override
  bool validateCrisisTransition() =>
      (super.noSuchMethod(
            Invocation.method(#validateCrisisTransition, []),
            returnValue: false,
          )
          as bool);

  @override
  void buyMetal() => super.noSuchMethod(
    Invocation.method(#buyMetal, []),
    returnValueForMissingStub: null,
  );

  @override
  void buyAutoclipper() => super.noSuchMethod(
    Invocation.method(#buyAutoclipper, []),
    returnValueForMissingStub: null,
  );

  @override
  void producePaperclip() => super.noSuchMethod(
    Invocation.method(#producePaperclip, []),
    returnValueForMissingStub: null,
  );

  @override
  void setSellPrice(double? newPrice) => super.noSuchMethod(
    Invocation.method(#setSellPrice, [newPrice]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> startNewGame(
    String? name, {
    _i16.GameMode? mode = _i16.GameMode.INFINITE,
    bool? syncToCloud = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startNewGame,
              [name],
              {#mode: mode, #syncToCloud: syncToCloud},
            ),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> saveGame(String? name, {bool? syncToCloud = true}) =>
      (super.noSuchMethod(
            Invocation.method(#saveGame, [name], {#syncToCloud: syncToCloud}),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> loadGame(String? name, {String? cloudId}) =>
      (super.noSuchMethod(
            Invocation.method(#loadGame, [name], {#cloudId: cloudId}),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> showCloudSaveSelector() =>
      (super.noSuchMethod(
            Invocation.method(#showCloudSaveSelector, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> saveOnImportantEvent() =>
      (super.noSuchMethod(
            Invocation.method(#saveOnImportantEvent, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> checkAndRestoreFromBackup() =>
      (super.noSuchMethod(
            Invocation.method(#checkAndRestoreFromBackup, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void updateLeaderboard() => super.noSuchMethod(
    Invocation.method(#updateLeaderboard, []),
    returnValueForMissingStub: null,
  );

  @override
  void showProductionLeaderboard() => super.noSuchMethod(
    Invocation.method(#showProductionLeaderboard, []),
    returnValueForMissingStub: null,
  );

  @override
  void showBankerLeaderboard() => super.noSuchMethod(
    Invocation.method(#showBankerLeaderboard, []),
    returnValueForMissingStub: null,
  );

  @override
  void showLeaderboard() => super.noSuchMethod(
    Invocation.method(#showLeaderboard, []),
    returnValueForMissingStub: null,
  );

  @override
  void showAchievements() => super.noSuchMethod(
    Invocation.method(#showAchievements, []),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, bool> getVisibleScreenElements() =>
      (super.noSuchMethod(
            Invocation.method(#getVisibleScreenElements, []),
            returnValue: <String, bool>{},
          )
          as Map<String, bool>);

  @override
  bool purchaseUpgrade(String? upgradeId) =>
      (super.noSuchMethod(
            Invocation.method(#purchaseUpgrade, [upgradeId]),
            returnValue: false,
          )
          as bool);

  @override
  void setContext(_i17.BuildContext? context) => super.noSuchMethod(
    Invocation.method(#setContext, [context]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleCrisisInterface() => super.noSuchMethod(
    Invocation.method(#toggleCrisisInterface, []),
    returnValueForMissingStub: null,
  );

  @override
  void togglePause() => super.noSuchMethod(
    Invocation.method(#togglePause, []),
    returnValueForMissingStub: null,
  );

  @override
  void checkMilestones() => super.noSuchMethod(
    Invocation.method(#checkMilestones, []),
    returnValueForMissingStub: null,
  );

  @override
  void activateXPBoost() => super.noSuchMethod(
    Invocation.method(#activateXPBoost, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i18.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i18.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
