// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJeRM2mEVBtBwzvITvnJg5tXjeOHg1Nf0',
    appId: '1:555184834356:web:e3aef82fdf74bf0055c761',
    messagingSenderId: '555184834356',
    projectId: 'paperclip-98294',
    authDomain: 'paperclip-98294.firebaseapp.com',
    storageBucket: 'paperclip-98294.firebasestorage.app',
    measurementId: 'G-P188MJ5BMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2OA70p2-RhwjkblhXva9yvNm81aKiqSY',
    appId: '1:555184834356:android:64e59406f0e91a5d55c761',
    messagingSenderId: '555184834356',
    projectId: 'paperclip-98294',
    storageBucket: 'paperclip-98294.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2gw2oORQCNrqdS49JIYanzG0B7uSL6co',
    appId: '1:555184834356:ios:59799cacd9b3873f55c761',
    messagingSenderId: '555184834356',
    projectId: 'paperclip-98294',
    storageBucket: 'paperclip-98294.firebasestorage.app',
    androidClientId: '555184834356-i44t0eruatgl6jo9po1m4h82q7nqs394.apps.googleusercontent.com',
    iosClientId: '555184834356-lgagvmkkpj79u80omihhj9854ekh8096.apps.googleusercontent.com',
    iosBundleId: 'com.example.paperclip2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2gw2oORQCNrqdS49JIYanzG0B7uSL6co',
    appId: '1:555184834356:ios:59799cacd9b3873f55c761',
    messagingSenderId: '555184834356',
    projectId: 'paperclip-98294',
    storageBucket: 'paperclip-98294.firebasestorage.app',
    androidClientId: '555184834356-i44t0eruatgl6jo9po1m4h82q7nqs394.apps.googleusercontent.com',
    iosClientId: '555184834356-lgagvmkkpj79u80omihhj9854ekh8096.apps.googleusercontent.com',
    iosBundleId: 'com.example.paperclip2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJeRM2mEVBtBwzvITvnJg5tXjeOHg1Nf0',
    appId: '1:555184834356:web:ab3cc45ff2885ccb55c761',
    messagingSenderId: '555184834356',
    projectId: 'paperclip-98294',
    authDomain: 'paperclip-98294.firebaseapp.com',
    storageBucket: 'paperclip-98294.firebasestorage.app',
    measurementId: 'G-5Y88PHLJ8C',
  );

}