// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkIRvxMkl6lL_6L5cfT1jkxPpMWV3Rmo0',
    appId: '1:426827215567:web:c682230a8ca2c0a74e7dba',
    messagingSenderId: '426827215567',
    projectId: 'paperclip2-2149',
    authDomain: 'paperclip2-2149.firebaseapp.com',
    databaseURL: 'https://paperclip2-2149-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'paperclip2-2149.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3XRQxBkiTJKm_vz1T1ldGYKEZXPnvb9g',
    appId: '1:426827215567:android:06864b5162458fc34e7dba',
    messagingSenderId: '426827215567',
    projectId: 'paperclip2-2149',
    databaseURL: 'https://paperclip2-2149-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'paperclip2-2149.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdwVx5n71p9Al7Z0BiJBmLdeveOXQSYYc',
    appId: '1:426827215567:ios:78518e2aba6b00694e7dba',
    messagingSenderId: '426827215567',
    projectId: 'paperclip2-2149',
    databaseURL: 'https://paperclip2-2149-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'paperclip2-2149.firebasestorage.app',
    iosBundleId: 'com.example.paperclip2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdwVx5n71p9Al7Z0BiJBmLdeveOXQSYYc',
    appId: '1:426827215567:ios:78518e2aba6b00694e7dba',
    messagingSenderId: '426827215567',
    projectId: 'paperclip2-2149',
    databaseURL: 'https://paperclip2-2149-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'paperclip2-2149.firebasestorage.app',
    iosBundleId: 'com.example.paperclip2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkIRvxMkl6lL_6L5cfT1jkxPpMWV3Rmo0',
    appId: '1:426827215567:web:7beef1e27db68de44e7dba',
    messagingSenderId: '426827215567',
    projectId: 'paperclip2-2149',
    authDomain: 'paperclip2-2149.firebaseapp.com',
    databaseURL: 'https://paperclip2-2149-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'paperclip2-2149.firebasestorage.app',
  );
}
