// Mocks generated by Mockito 5.4.6 from annotations
// in paperclip2/test/integration/cloud_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:paperclip2/services/cloud/cloud_persistence_port.dart' as _i2;
import 'package:paperclip2/services/cloud/models/cloud_world_detail.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCloudStatus_0 extends _i1.SmartFake implements _i2.CloudStatus {
  _FakeCloudStatus_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CloudPersistencePort].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudPersistencePort extends _i1.Mock
    implements _i2.CloudPersistencePort {
  MockCloudPersistencePort() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> pushById({
    required String? enterpriseId,
    required Map<String, dynamic>? snapshot,
    required Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pushById, [], {
              #enterpriseId: enterpriseId,
              #snapshot: snapshot,
              #metadata: metadata,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.CloudWorldDetail?> pullById({required String? enterpriseId}) =>
      (super.noSuchMethod(
            Invocation.method(#pullById, [], {#enterpriseId: enterpriseId}),
            returnValue: _i3.Future<_i4.CloudWorldDetail?>.value(),
          )
          as _i3.Future<_i4.CloudWorldDetail?>);

  @override
  _i3.Future<_i2.CloudStatus> statusById({required String? enterpriseId}) =>
      (super.noSuchMethod(
            Invocation.method(#statusById, [], {#enterpriseId: enterpriseId}),
            returnValue: _i3.Future<_i2.CloudStatus>.value(
              _FakeCloudStatus_0(
                this,
                Invocation.method(#statusById, [], {
                  #enterpriseId: enterpriseId,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.CloudStatus>);

  @override
  _i3.Future<List<_i2.CloudIndexEntry>> listParties() =>
      (super.noSuchMethod(
            Invocation.method(#listParties, []),
            returnValue: _i3.Future<List<_i2.CloudIndexEntry>>.value(
              <_i2.CloudIndexEntry>[],
            ),
          )
          as _i3.Future<List<_i2.CloudIndexEntry>>);

  @override
  _i3.Future<void> deleteById({required String? enterpriseId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteById, [], {#enterpriseId: enterpriseId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
